---
  - name: Check if the hadoop directory exists
    stat: path={{ installation_path }}/hadoop/
    register: stat_result

  - name: Include common tasks.
    include: setup.yml
    when: stat_result.stat.exists == False
    tags:
      - setup

  - name: Include tasks for master.
    include: master.yml
    when: "'master' in group_names"
    #when: stat_result.stat.exists == False
    tags:
     - master-install
